package org.dei.perla.core.fpc.base;

import org.dei.perla.core.engine.Script;
import org.dei.perla.core.message.Mapper;

/**
 * A wrapper object that stores the relation between an
 * {@link org.dei.perla.core.message.FpcMessage} type, identified by a
 * {@link Mapper} object, and the {@link Script} that must be employed to
 * process it.
 *
 * @author Guido Rota 31/03/15.
 */
public final class MessageScript {

    // Script object for managing the type of Messages identified by the
    // mapper field of this class
    private final Script script;

    private final Mapper mapper;

    // Synchronization flag. If set to true, the reception of the Message
    // identified by the mapper field of this class will compel the
    // NativePeriodicOperation to produce a new output sample.
    private final boolean sync;

    // Name of the variable that identifies the Message being processed
    // inside the script
    private final String variable;

    // Employed in the NativePeriodiOperation.OnScripHandler.merge method.
    // This field indicates the relative position of the data generated by
    // the script inside the global sample created by the periodic operation
    private final int base;

    public MessageScript(Script script, Mapper mapper, boolean sync,
            String variable, int base) {
        this.script = script;
        this.mapper = mapper;
        this.sync = sync;
        this.variable = variable;
        this.base = base;
    }

    public Script getScript() {
        return script;
    }

    public Mapper getMapper() {
        return mapper;
    }

    public boolean isSync() {
        return sync;
    }

    public String getVariable() {
        return variable;
    }

    public int getBase() {
        return base;
    }

}
