package org.dei.perla.core.fpc;

import java.util.List;

/**
 * An object for controlling the execution of an asynchronous {@link Fpc}
 * operation.
 *
 * @author Guido Rota (2014)
 *
 */
public interface Task {

	/**
	 * Returns a list of {@link Attribute}s generated by the asynchronous
	 * operation associated with this {@code Task}.
	 *
	 * @return {@link Attribute}s generated by the operation controlled by the
	 *         {@code Task}
	 */
	public List<Attribute> getAttributes();

	/**
	 * Indicates if a {@code Task} is running or not. A {@code Task} may stop
	 * for the following reasons:
	 * <ul>
	 * <li>No more {@link Sample}s are going to be produced by the {@link Fpc}</li>
	 * <li>The asynchronous operation was stopped by the user</li>
	 * <li>The {@link Fpc} has stopped</li>
	 * <li>An unrecoverable error prevents the creation of new {@link Sample}s</li>
	 * </ul>
	 *
	 * @return True if the {@code Task} is running, false otherwise
	 */
	public boolean isRunning();

	/**
	 * Stops the {@code Task}. This method has no effect if the {@code Task} is
	 * stopped
	 */
	public void stop();

}
