package org.dei.perla.channel.simulator;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Descriptor class used for defining the content of a single
 * <code>ChannelResponse</code> dynamically generated by a
 * <code>SimulatorChannel</code> instance.
 * 
 * <code>GeneratorDescriptor</code>s are composed by a unique identifier and a
 * flat list of fields, each of which is associated with a
 * <code>GeneratorFieldDescriptor</code> containing all information needed to
 * dynamically generate the corresponding field.
 * 
 * @author Guido Rota (2014)
 * 
 */
@XmlRootElement(name = "generator")
@XmlAccessorType(XmlAccessType.FIELD)
public class GeneratorDescriptor {

	@XmlAttribute(required = true)
	private String id;

	@XmlElementRef(name = "field", required = true)
	private List<GeneratorFieldDescriptor> fieldList = new ArrayList<>();

	public String getId() {
		return id;
	}

	public List<GeneratorFieldDescriptor> getFieldList() {
		return fieldList;
	}

}
